repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3
        args: [src]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  -     id: mypy
        args: [src]